name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_linux:
    name: Build the Tool for Linux
    uses: ../actions/build.yaml
    with:
      platform: ubuntu-latest
      outputDirName: "edpvp-log-prepare-linux"

  build_win:
    name: Build the Tool for Windows
    uses: ../actions/build.yaml
    with:
      platform: windows-latest
      outputDirName: "edpvp-log-prepare-windows"


  publish:

    needs:
      - build_linux
      - build_win
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: edpvp-log-prepare-linux, edpvp-log-prepare-windows
          token: ${{ secrets.GITHUB_TOKEN }}
